/* vim: set et ts=4 sts=4 sw=4 tw=72 : */
/* See the LICENSE file for the license of the project */
package uk.ac.cam.cl.git.database;

/**
 * Autogenerated methods from Exception.
 *
 * @author Kovacsics Robert &lt;rmk35@cam.ac.uk&gt;
 */
public class PushFailedException extends Exception
{
    static final long serialVersionUID = 3L;
    /**
     * @param message
     */
    public PushFailedException(String message)
    {
        super(message);
    }

    /**
     * @param cause
     */
    public PushFailedException(Throwable cause)
    {
        super(cause);
    }

    /**
     * @param message
     * @param cause
     */
    public PushFailedException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
